In [1]:
# Structure analysis after mini using lammps CG method for mini 
# Transfer all the calculations 
# Import project for post processing 
import numpy as np
%matplotlib inline
import matplotlib.pylab as plt
from pyiron import Project
pr = Project("/nfshome/deshmukh/pyiron/projects/NASICON/project/hena/hena_1/minimization")
import lammps_logfile

In [ ]:
q_rate = [42,15, 16, 8, 36, 31, 6, 21, 40, 22, 50] #42
q_tem = [523,573,623,673,723,773]
import random
# Crystal calculations 
#for i in q_rate: 
#    for j in q_tem:
#        job = pr['hena_1_struct_eq_%sk_%s'%(j,i)]
#        job.transfer_from_remote()
#        job.compress()


In [2]:
# This one will read the lammps log file from zipped file, without extracting the file itself 
import tarfile
import lammps_logfile
import os
import codecs
utf8reader = codecs.getreader('utf-8')

# ['Density', 'PotEng', 'Pxx', 'Pxy', 'Pxz', 'Pyy', 'Pyz', 'Pzz', 'Step', 'Temp', 'TotEng', 'Volume']


def tar_lammps(job,prop_1,prop_2):
    den = []
    step = []
    job_file_compressed = os.path.join(job.working_directory, [f for f in os.listdir(job.working_directory) if ".tar.bz2" in f][0])
    tar = tarfile.open(job_file_compressed, "r:bz2")
    for member in tar.getmembers():
        if 'log.lammps' == member.name:
            f = tar.extractfile(member)
            log = lammps_logfile.File(utf8reader(f))
            for i in range(log.get_num_partial_logs()):
                x = log.get(prop_1, run_num=i)
                y = log.get(prop_2, run_num=i)
                den.append(y)
                step.append(x)
    return step, den 

In [3]:
# This one will read the lammps log file from zipped file, without extracting the file itself 
import tarfile
import lammps_logfile
import os
import codecs
utf8reader = codecs.getreader('utf-8')

# ['Density', 'PotEng', 'Pxx', 'Pxy', 'Pxz', 'Pyy', 'Pyz', 'Pzz', 'Step', 'Temp', 'TotEng', 'Volume']


def tar_lammps_2(job,prop_1,prop_2):
    den = []
    step = []
    job_file_compressed = os.path.join(job, [f for f in os.listdir(job) if ".tar.bz2" in f][0])
    tar = tarfile.open(job_file_compressed, "r:bz2")
    for member in tar.getmembers():
        if 'log.lammps' == member.name:
            f = tar.extractfile(member)
            log = lammps_logfile.File(utf8reader(f))
            for i in range(log.get_num_partial_logs()):
                x = log.get(prop_1, run_num=i)
                y = log.get(prop_2, run_num=i)
                den.append(y)
                step.append(x)
    return step, den 

In [5]:
step,den = tar_lammps_2('/nfshome/deshmukh/pyiron/projects/NASICON/project/hena/hena_1/minimization/hena_1_struct_eq_300k_42_hdf5/hena_1_struct_eq_300k_42',"Step","Density")

In [6]:
step

[array([0.000e+00, 1.000e+02, 2.000e+02, ..., 4.998e+05, 4.999e+05,
        5.000e+05]),
 array([0.0000e+00, 1.0000e+02, 2.0000e+02, ..., 1.9998e+06, 1.9999e+06,
        2.0000e+06]),
 array([0.0000e+00, 1.0000e+02, 2.0000e+02, ..., 1.9998e+06, 1.9999e+06,
        2.0000e+06]),
 array([0.0000e+00, 1.0000e+02, 2.0000e+02, ..., 9.9998e+06, 9.9999e+06,
        1.0000e+07])]

In [3]:
#plt.plot(step[1][5000:17000],den[1][5000:17000])
#plt.axhline(y=np.mean(den[1][5000:17000]), color='red')

In [3]:
#list = [42,15, 16, 8, 36, 31, 6, 21, 40, 22, 50] # 42 is already transfered 
job_1 = pr['hena_1_struct_eq_300k_42']
step,den = tar_lammps(job_1,"Step","Density")

In [4]:
job_2 = pr['hena_1_struct_eq_300k_15']
step_2,den_2 = tar_lammps(job_2,"Step","Density")

In [5]:
job_3 = pr['hena_1_struct_eq_300k_16']
step_3,den_3 = tar_lammps(job_3,"Step","Density")

In [6]:
job_4 = pr['hena_1_struct_eq_300k_8']
step_4,den_4 = tar_lammps(job_4,"Step","Density")

In [7]:
job_5 = pr['hena_1_struct_eq_300k_36']
step_5,den_5 = tar_lammps(job_5,"Step","Density")

In [8]:
job_6 = pr['hena_1_struct_eq_300k_31']
step_6,den_6 = tar_lammps(job_6,"Step","Density")

In [9]:
job_7 = pr['hena_1_struct_eq_300k_6']
step_7,den_7 = tar_lammps(job_7,"Step","Density")
#step,volume = tar_lammps(job_1,"Step","PotEng")  

In [10]:
job_8 = pr['hena_1_struct_eq_300k_21']
step_8,den_8 = tar_lammps(job_8,"Step","Density")

In [11]:
job_9 = pr['hena_1_struct_eq_300k_40']
step_9,den_9 = tar_lammps(job_9,"Step","Density")

In [12]:
job_10 = pr['hena_1_struct_eq_300k_22']
step_10,den_10 = tar_lammps(job_10,"Step","Density")

In [13]:
job_11 = pr['hena_1_struct_eq_300k_50']
step_11,den_11 = tar_lammps(job_11,"Step","Density")

In [14]:
# Plot running avg. 
print(np.mean(den[1][5000:17000]), np.std(den[1][5000:17000]))

3.4721896442583335 0.010652732413894275


In [15]:
# Plot running avg. 
print(np.mean(den_2[1][5000:17000]), np.std(den_2[1][5000:17000]))

3.4305222588166666 0.010680453596879547


In [16]:
# Plot running avg. 
print(np.mean(den_3[1][5000:17000]), np.std(den_3[1][5000:17000]))

3.4503349355000004 0.01352088545115191


In [17]:
# Plot running avg. 
print(np.mean(den_4[1][5000:17000]), np.std(den_4[1][5000:17000]))

3.362611643875 0.01054267056112053


In [18]:
# Plot running avg. 
print(np.mean(den_5[1][5000:17000]), np.std(den_5[1][5000:17000]))

3.388393623808333 0.010641193835630268


In [19]:
# Plot running avg. 
print(np.mean(den_6[1][5000:17000]), np.std(den_6[1][5000:17000]))

3.420225730191667 0.010798999475969413


In [20]:
# Plot running avg. 
print(np.mean(den_7[1][5000:17000]), np.std(den_7[1][5000:17000]))

3.451258968075 0.010937489877491012


In [22]:
# Plot running avg. 
print(np.mean(den_8[1][5000:17000]), np.std(den_8[1][5000:17000]))

3.4390757772 0.010522287296379218


In [23]:
# Plot running avg. 
print(np.mean(den_9[1][5000:17000]), np.std(den_9[1][5000:17000]))

3.4221646033833335 0.011615269271770756


In [24]:
# Plot running avg. 
print(np.mean(den_10[1][5000:17000]), np.std(den_10[1][5000:17000]))

3.3707122976833332 0.011007100305747558


In [25]:
# Plot running avg. 
print(np.mean(den_11[1][5000:17000]), np.std(den_11[1][5000:17000]))

3.4357167421083337 0.010703848353712526


In [21]:
tm,den = tar_lammps(job_1,"Temp","Density")
temp = tm[1][5000:17000]
dens = den[1][5000:17000]

KeyboardInterrupt: 

In [14]:
tm_2,den_2 = tar_lammps(job_2,"Temp","Density")
temp_2 = tm_2[1][5000:17000]
dens_2 = den_2[1][5000:17000]

In [ ]:
tm_3,den_3 = tar_lammps(job_3,"Temp","Density")
temp_3 = tm_3[1][5000:17000]
dens_3 = den_3[1][5000:17000]

In [ ]:
tm_4,den_4 = tar_lammps(job_4,"Temp","Density")
temp_4 = tm_4[1][5000:17000]
dens_4 = den_4[1][5000:17000]

In [ ]:
tm_3,den_3 = tar_lammps(job_3,"Temp","Density")
temp_3 = tm_3[1][5000:17000]
dens_3 = den_3[1][5000:17000]

In [7]:
step,volume = tar_lammps(job_1,"Step","Volume")
st = step[1][5000:17000]
vol = volume[1][5000:17000]

In [12]:
pt,tot = tar_lammps(job_1,"PotEng","TotEng")
#pot_eng = pt[1][5000:17000]
#tot = tot[1][5000:17000]

In [11]:
print(np.mean(dens),np.std(dens))             # average density 

3.4721896442583335 0.010652732413894275


In [13]:
print(np.mean(temp),np.std(temp))  

300.0743988983333 11.148489438335517
